-- Create schemas

-- Create tables
CREATE TABLE IF NOT EXISTS Session
(
    ID INTEGER NOT NULL UNIQUE,
    GROUP INTEGER NOT NULL,
    Intersection INTEGER NOT NULL,
    Date DATE NOT NULL,
    Name VARCHAR(32) NOT NULL,
    Active BOOLEAN NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS Manager
(
    ID INTEGER NOT NULL UNIQUE,
    Email VARCHAR(32) NOT NULL,
    Password VARCHAR(32) NOT NULL,
    Active BOOLEAN NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS Group
(
    ID INTEGER NOT NULL UNIQUE,
    Manager INTEGER NOT NULL,
    Name VARCHAR(32) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS Crossing
(
    ID INTEGER NOT NULL,
    Session INTEGER NOT NULL,
    Type VARCHAR(32) NOT NULL,
    From VARCHAR(2) NOT NULL,
    To VARCHAR(2) NOT NULL,
    Time DATE NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS Intersection
(
    ID INTEGER NOT NULL UNIQUE,
    Street VARCHAR(32) NOT NULL,
    City VARCHAR(32) NOT NULL,
    State VARCHAR(2) NOT NULL,
    PRIMARY KEY(ID)
);


-- Create FKs
ALTER TABLE Session
    ADD    FOREIGN KEY (Intersection)
    REFERENCES Intersection(ID)
    MATCH SIMPLE
;
    
ALTER TABLE Session
    ADD    FOREIGN KEY (GROUP)
    REFERENCES Group(ID)
    MATCH SIMPLE
;
    
ALTER TABLE Group
    ADD    FOREIGN KEY (Manager)
    REFERENCES Manager(ID)
    MATCH SIMPLE
;
    
ALTER TABLE Crossing
    ADD    FOREIGN KEY (Session)
    REFERENCES Session(ID)
    MATCH SIMPLE
;
    

-- Create Indexes

